{% set name = "prettytable" %}
{% set version = "2.2.1" %}
{% set sha256 = "6d465005573a5c058d4ca343449a5b28c21252b86afcdfa168cdc6a440f0b24c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - setuptools
    - wcwidth
  run_constrained:
    - ptable >=9999

test:
  imports:
    - prettytable

about:
  home: http://code.google.com/p/prettytable
  license_file: COPYING
  license: BSD-3-Clause
  license_family: BSD
  summary: A simple Python library for easily displaying tabular data in a visually appealing ASCII table format
  dev_url: https://github.com/jazzband/prettytable
